name: quant data monitor html update

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 * * * *'

jobs:
  # 任务1：交易时间条件检查
  check:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    outputs:
      should_run: ${{ steps.check_time.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run trading day AND time checker
        id: check_time
        # 如果是手动触发，直接输出 true；否则执行检查
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "result=true" >> $GITHUB_OUTPUT
          else
            echo "result=$(python check_trading.py --check-day-only)" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check
    if: needs.check.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'  # 设置时区为上海

    steps:
      # Checkout main branch to get the latest code
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: main  # Checkout main branch

      - name: Set timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV

      # run update_data for 15min schedule
      - name: run update_data
        env:
          SQL_PASSWORDS: ${{ secrets.SQL_PASSWORDS }}
          SQL_HOST: ${{ secrets.SQL_HOST }}
        run: |
          pip install -r ./requirements.txt
          python3 ./update_display.py